# Generated by Django 5.2.5 on 2025-08-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.ImageField(default='food_images/default_food.jpg', upload_to='food_images/'),
        ),
    ]
